### ISSUE TITLE
Update extension on Assets Portal

### ISSUE THREAD

**Issue by AGulev** [defold/extension-review#7]
https://github.com/defold/awesome-defold/blob/master/assets/defreview.json

**Comment by britzl** [comment]
Oh. I thought I deleted that one. There's a new asset here:

https://github.com/defold/awesome-defold/blob/master/assets/review.json

**Comment by britzl** [comment]
I actually did: https://github.com/defold/awesome-defold/commit/5fe04eeae9bcfae48eff3aa3bc23429297298591

But the automation action to update repository stars etc brought it back

**Comment by AGulev** [comment]
Great!
